version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-stretch-browsers
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  test:
    docker:
      - image: circleci/node:6-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install npm packages
          command: npm install
      - run:
          name: Test the app
          command: npm test

  publish:
    docker:
      - image: circleci/node:6-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install npm packages
          command: npm install
      - run:
          name: Publish to NPM
          command: npm publish --access public

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
